(() => {
  "use strict";

  /*
   * =========================================================
   * GOMOKU WINNING LINE OVERLAY
   * =========================================================
   *
   * Purpose:
   * - Observe the winning-line stroke generated by app.js.
   * - Do NOT modify app.js.
   * - Do NOT depend on app.js internal state.
   * - Draw a refined overlay after the stones are rendered.
   *
   * IMPORTANT:
   * This file must be loaded BEFORE app.js.
   *
   * =========================================================
   */

  const WINNING_COLOR = "#d46d52";

  const state = {
    canvas: null,

    active: false,

    path: [],

    start: null,

    end: null,

    lineWidth: 0,

    raf: 0,

    pulseStart: 0,

    visible: false
  };


  /*
   * =========================================================
   * UTILITIES
   * =========================================================
   */

  function isWinningColor(value) {
    if (!value) {
      return false;
    }

    return normalizeColor(value) ===
      normalizeColor(WINNING_COLOR);
  }


  function normalizeColor(value) {
    return String(value)
      .trim()
      .toLowerCase()
      .replace(/\s+/g, "");
  }


  function getCanvas() {
    const canvas =
      document.querySelector("#boardCanvas");

    if (!canvas) {
      return null;
    }

    return canvas;
  }


  function getCanvasRect(canvas) {
    return canvas.getBoundingClientRect();
  }


  function getCssScale(canvas) {
    const rect =
      getCanvasRect(canvas);

    if (!rect.width) {
      return {
        x: 1,
        y: 1
      };
    }

    return {
      x:
        canvas.width /
        rect.width,

      y:
        canvas.height /
        rect.height
    };
  }


  /*
   * =========================================================
   * CANVAS DRAW INTERCEPTION
   * =========================================================
   */

  function installCanvasInterceptor() {
    if (
      !window.CanvasRenderingContext2D
    ) {
      return;
    }


    const proto =
      CanvasRenderingContext2D.prototype;


    if (
      proto.__gomokuWinningLineInstalled
    ) {
      return;
    }


    proto.__gomokuWinningLineInstalled =
      true;


    const originalMoveTo =
      proto.moveTo;


    const originalLineTo =
      proto.lineTo;


    const originalStroke =
      proto.stroke;


    const originalClearRect =
      proto.clearRect;


    const originalBeginPath =
      proto.beginPath;


    /*
     * Track the current path.
     */

    proto.beginPath =
      function (...args) {

        if (
          this.canvas?.id ===
          "boardCanvas"
        ) {
          this.__gomokuWinPath = [];
          this.__gomokuWinTracking = false;
        }


        return originalBeginPath.apply(
          this,
          args
        );

      };


    proto.moveTo =
      function (x, y) {

        if (
          this.canvas?.id ===
          "boardCanvas"
        ) {

          if (
            isWinningColor(
              this.strokeStyle
            )
          ) {

            this.__gomokuWinTracking = true;

            this.__gomokuWinPath = [
              {
                x,
                y
              }
            ];

          }

        }


        return originalMoveTo.call(
          this,
          x,
          y
        );

      };


    proto.lineTo =
      function (x, y) {

        if (
          this.canvas?.id ===
          "boardCanvas"
        ) {

          if (
            this.__gomokuWinTracking &&
            isWinningColor(
              this.strokeStyle
            )
          ) {

            this.__gomokuWinPath.push({
              x,
              y
            });

          }

        }


        return originalLineTo.call(
          this,
          x,
          y
        );

      };


    proto.stroke =
      function (...args) {

        if (
          this.canvas?.id ===
          "boardCanvas"
        ) {

          if (
            this.__gomokuWinTracking &&
            isWinningColor(
              this.strokeStyle
            ) &&
            this.__gomokuWinPath?.length >= 2
          ) {

            captureWinningLine(
              this,
              this.__gomokuWinPath,
              this.lineWidth
            );

          }

          this.__gomokuWinTracking =
            false;

        }


        return originalStroke.apply(
          this,
          args
        );

      };


    proto.clearRect =
      function (...args) {

        if (
          this.canvas?.id ===
          "boardCanvas"
        ) {

          clearWinningLine();

        }


        return originalClearRect.apply(
          this,
          args
        );

      };

  }


  /*
   * =========================================================
   * CAPTURE
   * =========================================================
   */

  function captureWinningLine(
    context,
    path,
    lineWidth
  ) {

    if (
      !path ||
      path.length < 2
    ) {
      return;
    }


    const canvas =
      context.canvas;


    if (!canvas) {
      return;
    }


    const first =
      path[0];


    const last =
      path[path.length - 1];


    state.canvas =
      canvas;


    state.start = {
      x: first.x,
      y: first.y
    };


    state.end = {
      x: last.x,
      y: last.y
    };


    state.lineWidth =
      Number(lineWidth) || 4;


    state.visible = true;


    state.pulseStart =
      performance.now();


    scheduleOverlay();

  }


  /*
   * =========================================================
   * CLEAR
   * =========================================================
   */

  function clearWinningLine() {

    state.visible =
      false;

    state.start =
      null;

    state.end =
      null;

    state.lineWidth =
      0;

    state.pulseStart =
      0;

    stopOverlay();

  }


  /*
   * =========================================================
   * OVERLAY
   * =========================================================
   */

  function createOverlay() {

    let overlay =
      document.querySelector(
        "#gomokuWinningLineOverlay"
      );


    if (overlay) {
      return overlay;
    }


    overlay =
      document.createElement(
        "canvas"
      );


    overlay.id =
      "gomokuWinningLineOverlay";


    overlay.setAttribute(
      "aria-hidden",
      "true"
    );


    overlay.style.position =
      "fixed";


    overlay.style.pointerEvents =
      "none";


    overlay.style.zIndex =
      "15";


    overlay.style.display =
      "none";


    overlay.style.width =
      "0";


    overlay.style.height =
      "0";


    document.body.appendChild(
      overlay
    );


    return overlay;

  }


  function resizeOverlay(
    overlay,
    rect
  ) {

    const dpr =
      Math.min(
        window.devicePixelRatio || 1,
        3
      );


    overlay.width =
      Math.max(
        1,
        Math.round(
          rect.width * dpr
        )
      );


    overlay.height =
      Math.max(
        1,
        Math.round(
          rect.height * dpr
        )
      );


    overlay.style.left =
      `${rect.left}px`;


    overlay.style.top =
      `${rect.top}px`;


    overlay.style.width =
      `${rect.width}px`;


    overlay.style.height =
      `${rect.height}px`;


    const ctx =
      overlay.getContext(
        "2d"
      );


    ctx.setTransform(
      dpr,
      0,
      0,
      dpr,
      0,
      0
    );

  }


  function drawOverlay() {

    if (
      !state.visible ||
      !state.canvas ||
      !state.start ||
      !state.end
    ) {
      return;
    }


    const canvas =
      state.canvas;


    const overlay =
      createOverlay();


    const rect =
      getCanvasRect(
        canvas
      );


    if (
      !rect.width ||
      !rect.height
    ) {
      return;
    }


    resizeOverlay(
      overlay,
      rect
    );


    const scale =
      getCssScale(
        canvas
      );


    /*
     * app.js coordinates are in CSS-pixel
     * coordinates because it calls setTransform(dpr,...)
     * before rendering.
     *
     * Convert them into the overlay's local coordinates.
     */

    const startX =
      state.start.x /
      scale.x;

    const startY =
      state.start.y /
      scale.y;

    const endX =
      state.end.x /
      scale.x;

    const endY =
      state.end.y /
      scale.y;


    const ctx =
      overlay.getContext(
        "2d"
      );


    const width =
      Math.max(
        3,
        state.lineWidth /
        scale.x
      );


    ctx.clearRect(
      0,
      0,
      rect.width,
      rect.height
    );


    /*
     * ---------------------------------------------------------
     * Outer glow
     * ---------------------------------------------------------
     */

    ctx.save();


    ctx.globalAlpha =
      0.20;


    ctx.strokeStyle =
      "#d46d52";


    ctx.lineWidth =
      width * 2.8;


    ctx.lineCap =
      "round";


    ctx.lineJoin =
      "round";


    ctx.shadowColor =
      "rgba(212,109,82,0.75)";


    ctx.shadowBlur =
      Math.max(
        8,
        width * 2.4
      );


    ctx.beginPath();


    ctx.moveTo(
      startX,
      startY
    );


    ctx.lineTo(
      endX,
      endY
    );


    ctx.stroke();


    ctx.restore();


    /*
     * ---------------------------------------------------------
     * Main line
     * ---------------------------------------------------------
     */

    ctx.save();


    ctx.globalAlpha =
      0.94;


    ctx.strokeStyle =
      "#d46d52";


    ctx.lineWidth =
      width;


    ctx.lineCap =
      "round";


    ctx.lineJoin =
      "round";


    ctx.beginPath();


    ctx.moveTo(
      startX,
      startY
    );


    ctx.lineTo(
      endX,
      endY
    );


    ctx.stroke();


    ctx.restore();


    /*
     * ---------------------------------------------------------
     * Highlight
     * ---------------------------------------------------------
     */

    ctx.save();


    ctx.globalAlpha =
      0.38;


    ctx.strokeStyle =
      "#ffd7ca";


    ctx.lineWidth =
      Math.max(
        1.2,
        width * 0.28
      );


    ctx.lineCap =
      "round";


    ctx.beginPath();


    ctx.moveTo(
      startX,
      startY
    );


    ctx.lineTo(
      endX,
      endY
    );


    ctx.stroke();


    ctx.restore();


    /*
     * ---------------------------------------------------------
     * End caps
     * ---------------------------------------------------------
     */

    const pulse =
      0.5 +
      Math.sin(
        (
          performance.now() -
          state.pulseStart
        ) /
        360
      ) *
      0.5;


    const capRadius =
      Math.max(
        4,
        width * 0.72
      );


    ctx.save();


    ctx.globalAlpha =
      0.55 +
      pulse * 0.25;


    ctx.fillStyle =
      "#d46d52";


    ctx.shadowColor =
      "rgba(212,109,82,0.65)";


    ctx.shadowBlur =
      Math.max(
        7,
        width * 1.8
      );


    ctx.beginPath();


    ctx.arc(
      startX,
      startY,
      capRadius,
      0,
      Math.PI * 2
    );


    ctx.fill();


    ctx.beginPath();


    ctx.arc(
      endX,
      endY,
      capRadius,
      0,
      Math.PI * 2
    );


    ctx.fill();


    ctx.restore();


    overlay.style.display =
      "block";

  }


  /*
   * =========================================================
   * FRAME LOOP
   * =========================================================
   */

  function scheduleOverlay() {

    if (
      state.raf
    ) {
      return;
    }


    state.raf =
      requestAnimationFrame(
        () => {

          state.raf =
            0;

          if (
            state.visible
          ) {

            drawOverlay();

            scheduleOverlay();

          }

        }
      );

  }


  function stopOverlay() {

    if (
      state.raf
    ) {

      cancelAnimationFrame(
        state.raf
      );

      state.raf =
        0;

    }


    const overlay =
      document.querySelector(
        "#gomokuWinningLineOverlay"
      );


    if (overlay) {

      const ctx =
        overlay.getContext(
          "2d"
        );


      ctx.clearRect(
        0,
        0,
        overlay.width,
        overlay.height
      );


      overlay.style.display =
        "none";

    }

  }


  /*
   * =========================================================
   * SCREEN / RESIZE MONITOR
   * =========================================================
   */

  function installObservers() {

    window.addEventListener(
      "resize",
      () => {

        if (
          state.visible
        ) {

          drawOverlay();

        }

      },
      {
        passive: true
      }
    );


    window.addEventListener(
      "orientationchange",
      () => {

        window.setTimeout(
          () => {

            if (
              state.visible
            ) {

              drawOverlay();

            }

          },
          120
        );

      },
      {
        passive: true
      }
    );


    document.addEventListener(
      "visibilitychange",
      () => {

        if (
          document.visibilityState ===
          "visible" &&
          state.visible
        ) {

          drawOverlay();

        }

      }
    );

  }


  /*
   * =========================================================
   * INIT
   * =========================================================
   */

  installCanvasInterceptor();

  installObservers();

})();
